copy target\clschina-common-1.0.jar ..\..\saofenbao.git\erp\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\feili\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\feiliadmin\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\lipince\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\erp-api\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\liduonet\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\saofenbao\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\saofenbaoadmin\src\main\webapp\WEB-INF\lib /y
copy target\clschina-common-1.0.jar ..\..\saofenbao.git\saofenbaovendor\src\main\webapp\WEB-INF\lib /y
